title: Cheetah
description: An Experiment Harness and Campaign Management System for Studying In Situ Data Management for Scientific Applications <br> ECP CODAR
theme: jekyll-theme-cayman
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

