title: Cheetah
description: An Experiment Harness and Campaign Management System for In Situ Data Management <br> ECP CODAR
theme: jekyll-theme-hacker
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

