run_local:
	run/local.sh
run_summit:
	run/summit.sh
run_theta:
	run/theta.sh
status_local:
	status/local.sh
status_summit:
	status/summit.sh
status_theta:
	status/theta.sh
test_local:
	tests/local.sh
test_summit:
	tests/summit.sh
test_theta:
	tests/theta.sh
clean:
	rm -rf local summit theta *~ __pycache__ *.csv */*~



