
export CODAR_CHEETAH_GROUP_WALLTIME="1800"
export CODAR_CHEETAH_GROUP_MAX_PROCS="1"

export CODAR_CHEETAH_SCHEDULER_ACCOUNT=""
# queue on PBS, partition on SLURM
export CODAR_CHEETAH_SCHEDULER_QUEUE=""
# SLURM specific options
export CODAR_CHEETAH_SCHEDULER_CONSTRAINT=""
export CODAR_CHEETAH_SCHEDULER_LICENSE=""
export CODAR_CHEETAH_SCHEDULER_RESERVATION=""

export CODAR_CHEETAH_CAMPAIGN_NAME="codar.cheetah.e-small-one-node"

export CODAR_CHEETAH_GROUP_NAME="all-methods-small"
export CODAR_CHEETAH_GROUP_NODES="1"
export CODAR_CHEETAH_GROUP_NODE_EXCLUSIVE="False"
export CODAR_CHEETAH_GROUP_PROCESSES_PER_NODE="1"
export CODAR_CHEETAH_MACHINE_NAME="local"
