#!/bin/bash

cd "$PBS_O_WORKDIR"

source ../campaign-env.sh
source group-env.sh

if [ -f "$CODAR_CHEETAH_MACHINE_CONFIG" ]; then
    source "$CODAR_CHEETAH_MACHINE_CONFIG"
fi

# Main application run
"$CODAR_WORKFLOW_SCRIPT" --runner=$CODAR_WORKFLOW_RUNNER \
 --max-procs=$CODAR_CHEETAH_GROUP_MAX_PROCS \
 --producer-input-file=fobs.json \
 --log-file=codar.FOBrun.log \
 --log-level=$CODAR_CHEETAH_WORKFLOW_LOG_LEVEL

# TODO: Post processing
#"{post_processing}" "{group_directory}"
