
export CODAR_CHEETAH_GROUP_WALLTIME="300"
export CODAR_CHEETAH_GROUP_MAX_PROCS="2"

export CODAR_CHEETAH_SCHEDULER_ACCOUNT="csc299"
# queue on PBS, partition on SLURM
export CODAR_CHEETAH_SCHEDULER_QUEUE=""
# SLURM specific options
export CODAR_CHEETAH_SCHEDULER_CONSTRAINT=""
export CODAR_CHEETAH_SCHEDULER_LICENSE=""
export CODAR_CHEETAH_SCHEDULER_RESERVATION=""

export CODAR_CHEETAH_CAMPAIGN_NAME="codar.cheetah.coupling-example"

export CODAR_CHEETAH_GROUP_NAME="sg-1"
export CODAR_CHEETAH_GROUP_NODES="1"
export CODAR_CHEETAH_GROUP_NODE_EXCLUSIVE="True"
export CODAR_CHEETAH_GROUP_PROCESSES_PER_NODE="42"
export CODAR_CHEETAH_MACHINE_NAME="summit"
