#!/bin/bash

cd "$LS_SUBCWD"

source ../campaign-env.sh
source group-env.sh

if [ -f "$CODAR_CHEETAH_MACHINE_CONFIG" ]; then
    source "$CODAR_CHEETAH_MACHINE_CONFIG"
fi

if [ -n "$CODAR_CHEETAH_APP_CONFIG" ]; then
    source "$CODAR_CHEETAH_APP_CONFIG"
fi

if [ -n "$CODAR_CHEETAH_UMASK" ]; then
    umask "$CODAR_CHEETAH_UMASK"
fi

start=$(date +%s)

# Main application run
"$CODAR_PYTHON" "$CODAR_WORKFLOW_SCRIPT" --runner=$CODAR_WORKFLOW_RUNNER \
 --producer-input-file=fobs.json \
 --max-nodes=$CODAR_CHEETAH_GROUP_NODES \
 --processes-per-node=$CODAR_CHEETAH_GROUP_PROCESSES_PER_NODE \
 --log-file=codar.FOBrun.log \
 --machine-name=$CODAR_CHEETAH_MACHINE_NAME \
 --status-file=codar.workflow.status.json \
 --log-level=$CODAR_CHEETAH_WORKFLOW_LOG_LEVEL \
 >codar.workflow.stdout 2>codar.workflow.stderr

end=$(date +%s)
echo $(($end - $start)) > codar.cheetah.walltime.txt

# TODO: Post processing
#"{post_processing}" "{group_directory}"
